extern NSString * const OQ_AUTHENTICATE_URL;
extern NSString * const OQ_AUTH_TOKEN_KEY;
extern NSString * const OQ_APP_TITLE;
extern NSString * const OQ_USER_DEFAULTS_KEY_USERNAME;
extern NSString * const OQ_SHOW_MY_CURRENT_LOCATION_SEGUE_IDENTIFIER;
extern NSString * const OQ_SHOW_MENU_SEGUE_IDENTIFIER;
extern NSString * const OQ_SHOW_ALL_LOCATIONS_SEGUE_IDENTIFIER;
extern NSString * const OQ_SHOW_LOCATION_SEGUE_IDENTIFIER;
extern double const OQ_DISTANCE_TO_DEFER_LOCATION_UPDATE_IN_METERS;